### ISSUE TITLE
Ability to change fee for trc-20 transfer

### ISSUE THREAD

**Issue by the-tinderbox** [fullstackwang/tron-grpc#1] opened 2023-02-15 08:10 UTC
Hi! Using your library faced problem with sending trc-20 tokens. The problem is OUT OF ENERGY, so it would be great if you make an ability to change fee option! Thx!

**Comment by nomadalex** [comment] 2023-02-19 11:20
fixed in [6696ad5](https://github.com/fullstackwang/tron-grpc/commit/6696ad5d6ac4a0b3daa5cd014c4600a0c672e5e9)

**Closed as completed by nomadalex** 2023-02-19 11:20 UTC

**Comment by nomadalex** [comment] 2023-02-19 11:23
It is caused by Dynamic Energy Model introduced recently.
